# Config file for Air

root = "."
tmp_dir = ""

[build]
  include_ext = ["go", "tpl", "tmpl", "html", "css"]
  includeDir = ["."]           # Include all directories in the current directory
  followSymlink = true         # Follow symlinks in the directory

[color]
  main = "magenta"             # Color for the main section
  watcher = "cyan"             # Color for the watcher section
  building = "yellow"          # Color for the building section
  running = "green"            # Color for the running section
  logging = "blue"             # Color for the logging section
  error = "red"                # Color for errors
